# pre process
ds_size: 0.1
maximum_corner_num: 100 #500

# key points
plane_detection_thre: 0.01 #svd分解最小特征值
plane_merge_normal_thre: 0.3 #法线之差或者和
voxel_size: 1 # 栅格尺寸
voxel_init_num: 100 # 栅格至少有10个点才能进行平面的拟合
proj_image_resolution: 0.25
proj_dis_min: 0
proj_dis_max: 5
corner_thre: 10

# std descriptor
descriptor_near_num: 20 #最近的20个corner之间构建描述子
descriptor_min_len: 2
descriptor_max_len: 30 #30
non_max_suppression_radius: 2 #2m内搜索其他角点，如果像素梯度不如自己，踢掉
std_side_resolution: 0.2 #离散化的时候的分辨率

# candidate search
skip_near_num: 3 #最近一定帧数不找回环
candidate_num: 50
sub_frame_num: 1
vertex_diff_threshold: 0.8 #对比描述子相似性的参数
rough_dis_threshold: 0.05 #允许三角形周长误差的比例
normal_threshold: 0.3
dis_threshold: 0.5 #这两个参数用在面和面匹配
icp_threshold: 0.2
